language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
    - SYMFONY_VERSION=2.8.* TEST_COMMAND="phpunit"

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - env: SYMFONY_VERSION=3.0.*

    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.1.*
        - php: 5.6
          env: SYMFONY_VERSION=2.2.*
        - php: 5.6
          env: SYMFONY_VERSION=2.3.*
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 5.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="phpunit --coverage-text --coverage-clover=build/coverage.xml" SYMFONY_VERSION=2.3.*

before_install:
    - travis_retry composer self-update

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
